### ISSUE TITLE
Gray out past events

### ISSUE THREAD

**Issue by dabch** [dabch/epaper-calendar#4]
Some indication of the current time would be cool, e.g. slightly graying out the hours of the current day that have already passed.

**Comment by dabch** [comment]
I tried this, it looks really ugly because of the bad resolution of the screen and the fact that there are only b&w, no gray scale.

**Comment by nyxaria** [comment]
What about making the current one red?

**Comment by dabch** [comment]
Unfortunately the E-Paper Screen I am using is black/white only. But sure this would be an option with a three-color screen
